name: Check for stale Markdown links

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run link check
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        check-modified-files-only: 'yes'
